# Generated by Django 2.1.13 on 2020-03-06 05:57

import backend.media_filer.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerImage',
            fields=[
                ('_height', models.IntegerField(blank=True, null=True)),
                ('_width', models.IntegerField(blank=True, null=True)),
                ('default_alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='default alt text')),
                ('default_caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='default caption')),
                ('subject_location', models.CharField(blank=True, default='', max_length=64, verbose_name='subject location')),
                ('file_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='backend_media_filer_filerimage_file', serialize=False, to='filer.File')),
                ('cropping', backend.media_filer.fields.CroppableFilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.FILER_IMAGE_MODEL)),
            ],
            bases=('filer.file',),
        ),
        migrations.CreateModel(
            name='FilerFolder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('filer.folder',),
        ),
    ]
