# Generated by Django 2.1.13 on 2020-02-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0012_filerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilerFolder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('filer.folder',),
        ),
        migrations.CreateModel(
            name='ProxyFilerImage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('filer.filerimage',),
        ),
    ]
