# Generated by Django 2.1.13 on 2020-03-06 06:00

import backend.media_filer.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_media_filer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerimage',
            name='cropping',
            field=backend.media_filer.fields.CroppableFilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
