# Generated by Django 2.1.13 on 2020-03-06 06:32

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend_media_filer', '0002_auto_20200306_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('file_ptr', '30x30', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
