# Generated by Django 2.1.13 on 2020-03-17 05:31

import backend.media_filer.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend_media_filer', '0003_auto_20200306_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerimage',
            name='image_ptr',
            field=backend.media_filer.fields.CroppableFilerImageField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='backend_media_filer_filerimage_file', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filerimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('file_ptr__file', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
